version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: prompt2video
      POSTGRES_USER: prompt2video
      POSTGRES_PASSWORD: password123
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U prompt2video']
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for job queue
  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 3s
      retries: 5

  # Prompt2Video API
  api:
    build: .
    ports:
      - '8080:8080'
    environment:
      - PORT=8080
      - DATABASE_URL=postgres://prompt2video:password123@postgres:5432/prompt2video?sslmode=disable
      - REDIS_URL=redis://redis:6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - VIDEO_STORAGE=/app/storage/videos
      - WORKER_COUNT=3
    volumes:
      - video_storage:/app/storage/videos
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
  video_storage:
